### ISSUE TITLE
getGeo DoS

### ISSUE THREAD

**Issue by marcinlacina** [marcinlacina/debian-conf#3]
Piszę po polsku, bo po angielsku się nie wysłowię. Metoda getGeo pobiera obiekt z api za pomocą file_get_contents i go zwraca - spoko. Tylko że potem jest wywoływana dwa razy w metodzie __toString więc dwa razy pobiera ten sam obiekt, wysyłając przy okazji dwa takie same requesty do api. Moim zdaniem to bez sensu.

**Comment by efik** [comment]
Zrobiłem prostego fixa, moim zdaniem trzymanie klasy i kodu w 1pliku jest bez sensu :d 
Zaś z 3 strony, klasa jest zależna od tamtego api :>
